### ISSUE TITLE
Continous Deployment?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/phoenix-liveview-chat-example#136]
I thought the application was deployed as soon as a PR was merged, however it doesn't seem to be the case, as #135 as just been merged.
![image](https://github.com/dwyl/phoenix-liveview-chat-example/assets/6057298/c6fbac32-66c2-42a9-909c-c3318d4a2993)

- [ ]  Add Github action to deployed the application on Fly

I expect that we might have some error during the first deploy as Fly is using the v2 version now, so we might need to update the `fly.toml` file

**Comment by nelsonic** [comment]
Sounds good. Thanks @SimonLab 👍

**Comment by SimonLab** [comment]
Fly documentation for Continuos Deployment, https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/#speed-run-your-way-to-continuous-deployment :
![image](https://github.com/dwyl/phoenix-liveview-chat-example/assets/6057298/059ec9c5-dd96-4bbc-8f5b-099869650d7b)

**Comment by nelsonic** [comment]
PR merged. Thanks again @SimonLab 👌
