### ISSUE TITLE
Add Presence

### ISSUE THREAD

**Issue by SimonLab** [dwyl/phoenix-liveview-chat-example#18]
Use [Presence](https://hexdocs.pm/phoenix/Phoenix.Presence.html) to display of loggedin people.

**Comment by nelsonic** [comment]
https://github.com/dwyl/learn-phoenix-framework/issues/145#issuecomment-961061281

**Comment by SimonLab** [comment]
## Add Presence
We first need to add the presence features to the application. The first part of the documentation explains how to do this https://hexdocs.pm/phoenix/Phoenix.Presence.html#module-example-usage
  - Create a new `presence.ex` file in `lib/liveview_chat/` folder with the following content:
```elixir
defmodule LiveviewChat.Presence do
  use Phoenix.Presence,
    otp_app: :liveview_chat,
    pubsub_server: LiveviewChat.PubSub
end
```

Then in `lib/liveview_chat/application.ex` we start Presence by adding it to the list of children in the `start` function:

```elixir
    children = [
      # Start the Ecto repository
      LiveviewChat.Repo,
      # Start the Telemetry supervisor
      LiveviewChatWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: LiveviewChat.PubSub},
      # Presence
      LiveviewChat.Presence,
      # Start the Endpoint (http/https)
      LiveviewChatWeb.Endpoint
      # Start a worker by calling: LiveviewChat.Worker.start_link(arg)
      # {LiveviewChat.Worker, arg}
    ]
```
Now we can use the Presence features to listen to people using the app.

## Track new user on `mount`

We know that a new user is using the chat message when the `mount` liveview function is called.
We use the [track/3](https://hexdocs.pm/phoenix/Phoenix.Presence.html#c:track/4) function to know the status of a user.

```elixir
     if socket.assigns.loggedin do
        person_id = socket.assigns.person["id"]
        person_name = socket.assigns.person["givenName"]

        {:ok, _} =
          Presence.track(self(), "liveview_chat_presence", person_id, %{name: person_name})
      end

```
At the moment we only track loggedin people, so we use

## Listen for join/leave event

**Comment by SimonLab** [comment]
PR ready for review at https://github.com/dwyl/phoenix-liveview-chat-example/pull/19

**Comment by SimonLab** [comment]
deployed at https://liveview-chat-example.herokuapp.com/

**Comment by nelsonic** [comment]
Superb addition. Thanks @SimonLab 👍
