### ISSUE TITLE
Chore: Heroku Deploy Pipeline not auto-deploying [or manual either!]

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-liveview-chat-example#47]
@SimonLab the Heroku app is not auto-deploying so doesn't have the `Tailwind` enhancements #4 

https://liveview-chat-example.herokuapp.com/
![image](https://user-images.githubusercontent.com/194400/174987608-8747a56b-ac73-4f6e-a2cf-b780c3a4cd20.png)

https://dashboard.heroku.com/apps/liveview-chat-example
Last deployed Dec 2021.

I tried doing a _manual_ deploy but got the following error:

![image](https://user-images.githubusercontent.com/194400/174987998-a3b17bbc-a68d-43b6-a397-ad9988897069.png)

Please check as I think you are the "owner" of the app ... Not urgent. `#NiceToHave` 🤞 (thanks!)

**Comment by SimonLab** [comment]
> Please check as I think you are the "owner" of the app ... Not urgent. #NiceToHave crossed_fingers (thanks!)

The app belongs to you @nelsonic (you are the owner apparently). I have also the same error. I can try to reconnect Github to Heroku, otherwise maybe we could use Fly.io

**Comment by nelsonic** [comment]
@SimonLab thanks for doing that. Defo wasn't urgent.
But appears to be working with auth [hosted on Heroku]:
![image](https://user-images.githubusercontent.com/194400/174997162-41752e57-b065-4331-932a-0a6ec2b69c04.png)

Updated the `AUTH_API_KEY` using https://auth.dwyl.com/apps/6
and restarted the Heroku app. ⏳ 

Closing. Thanks. 👍
